package com.devpro.yuubook.utils;

public interface Constant {
	Integer HOME_LIMITED_PRODUCT_AUTHOR = 3;
	Integer HOME_LIMITED_PRODUCT_CATEGORY = 6;
	Integer HOME_LIMITED_PRODUCT_SUBCATEGORY = 8;
	Integer HOME_LIMITED_PRODUCT_HOT = 10;
	Integer LIMITED_PRODUCT_HOT = 8;
	Integer LIMITED_PRODUCT_CATEGORY = 8;
	Integer LIMITED_PRODUCT_EACH_CATEGORY = 4;
}
